In [1]:
from tensorflow.keras.preprocessing.text import one_hot # type: ignore


In [2]:
# sentences
sent=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',
]

In [3]:
#Define the vocabulary size
voc_size=10000

In [4]:
#One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr


[[4862, 6857, 8603, 3475],
 [4862, 6857, 8603, 1124],
 [4862, 6263, 8603, 7235],
 [2686, 8894, 8647, 506, 8782],
 [2686, 8894, 8647, 506, 7769],
 [9473, 4862, 9419, 8603, 1423],
 [9969, 6161, 9882, 506]]

In [5]:
# word embedding

from tensorflow.keras.layers import Embedding  # type: ignore
from tensorflow.keras.utils import pad_sequences # type: ignore
from tensorflow.keras.models import Sequential # type: ignore

In [6]:
import numpy as np

In [7]:
# set squence lenght
sent_lenght=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_lenght)
print(embedded_docs)

[[   0    0    0    0 4862 6857 8603 3475]
 [   0    0    0    0 4862 6857 8603 1124]
 [   0    0    0    0 4862 6263 8603 7235]
 [   0    0    0 2686 8894 8647  506 8782]
 [   0    0    0 2686 8894 8647  506 7769]
 [   0    0    0 9473 4862 9419 8603 1423]
 [   0    0    0    0 9969 6161 9882  506]]


In [8]:
# feature representation
dim=10


In [14]:
dummy_input = np.zeros((1, sent_lenght), dtype=int)  # shape: (batch_size=1, sequence_length)
model(dummy_input) # type: ignore
model.summary() # type: ignore

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (7, 8, 10)             │       100,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ (7, 64)                │         4,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (7, 1)                 │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 104,865 (409.63 KB)

 Trainable params: 104,865 (409.63 KB)

 Non-trainable params: 0 (0.00 B)

In [15]:
model.predict(embedded_docs) # type: ignore

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 184ms/step


array([[0.47681615],
       [0.46887514],
       [0.49167612],
       [0.48984924],
       [0.5024372 ],
       [0.48500568],
       [0.49952435]], dtype=float32)

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 4862, 6857, 8603, 3475])

In [17]:
model.predict(np.array([embedded_docs[0]])) # type: ignore

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step


array([[0.47681612]], dtype=float32)