In [3]:
from tensorflow.keras.preprocessing.text import one_hot # type: ignore


In [2]:
# sentences
sent=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',
]

In [4]:
#Define the vocabulary size
voc_size=10000

In [5]:
#One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr


[[357, 9311, 8336, 365],
 [357, 9311, 8336, 1198],
 [357, 3108, 8336, 2548],
 [7662, 5725, 3688, 17, 4309],
 [7662, 5725, 3688, 17, 5315],
 [3172, 357, 6844, 8336, 32],
 [111, 896, 3783, 17]]

In [7]:
# word embedding

from tensorflow.keras.layers import Embedding  # type: ignore
from tensorflow.keras.utils import pad_sequences # type: ignore
from tensorflow.keras.models import Sequential # type: ignore

In [8]:
import numpy as np

In [10]:
# set squence lenght
sent_lenght=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_lenght)
print(embedded_docs)

[[   0    0    0    0  357 9311 8336  365]
 [   0    0    0    0  357 9311 8336 1198]
 [   0    0    0    0  357 3108 8336 2548]
 [   0    0    0 7662 5725 3688   17 4309]
 [   0    0    0 7662 5725 3688   17 5315]
 [   0    0    0 3172  357 6844 8336   32]
 [   0    0    0    0  111  896 3783   17]]


In [11]:
# feature representation
dim=10


In [ ]:
dummy_input = np.zeros((1, sent_lenght), dtype=int)  # shape: (batch_size=1, sequence_length)
model(dummy_input) # type: ignore
model.summary() # type: ignore

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (7, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.predict(embedded_docs) # type: ignore

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 178ms/step


array([[[-0.01445148, -0.04827629,  0.02324792, -0.02093254,
         -0.02930456, -0.01990524,  0.0145203 , -0.02718933,
         -0.03212751, -0.02670466],
        [-0.01445148, -0.04827629,  0.02324792, -0.02093254,
         -0.02930456, -0.01990524,  0.0145203 , -0.02718933,
         -0.03212751, -0.02670466],
        [-0.01445148, -0.04827629,  0.02324792, -0.02093254,
         -0.02930456, -0.01990524,  0.0145203 , -0.02718933,
         -0.03212751, -0.02670466],
        [-0.01445148, -0.04827629,  0.02324792, -0.02093254,
         -0.02930456, -0.01990524,  0.0145203 , -0.02718933,
         -0.03212751, -0.02670466],
        [-0.01024283,  0.03333897, -0.03597488, -0.03536908,
         -0.01081369, -0.0326545 ,  0.03283647, -0.04393221,
         -0.04876666,  0.00742389],
        [-0.00184723, -0.01144005,  0.00779573, -0.02412662,
          0.01283425,  0.00128699,  0.00562125, -0.0260524 ,
          0.01661733, -0.01676977],
        [ 0.03957203,  0.00710893, -0.0075979 , -0.0

In [26]:
embedded_docs[0]

array([   0,    0,    0,    0,  357, 9311, 8336,  365], dtype=int32)

In [ ]:
model.predict(np.array([embedded_docs[0]])) # type: ignore

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step


array([[[-0.01445148, -0.04827629,  0.02324792, -0.02093254,
         -0.02930456, -0.01990524,  0.0145203 , -0.02718933,
         -0.03212751, -0.02670466],
        [-0.01445148, -0.04827629,  0.02324792, -0.02093254,
         -0.02930456, -0.01990524,  0.0145203 , -0.02718933,
         -0.03212751, -0.02670466],
        [-0.01445148, -0.04827629,  0.02324792, -0.02093254,
         -0.02930456, -0.01990524,  0.0145203 , -0.02718933,
         -0.03212751, -0.02670466],
        [-0.01445148, -0.04827629,  0.02324792, -0.02093254,
         -0.02930456, -0.01990524,  0.0145203 , -0.02718933,
         -0.03212751, -0.02670466],
        [-0.01024283,  0.03333897, -0.03597488, -0.03536908,
         -0.01081369, -0.0326545 ,  0.03283647, -0.04393221,
         -0.04876666,  0.00742389],
        [-0.00184723, -0.01144005,  0.00779573, -0.02412662,
          0.01283425,  0.00128699,  0.00562125, -0.0260524 ,
          0.01661733, -0.01676977],
        [ 0.03957203,  0.00710893, -0.0075979 , -0.0